<?php

return [
  'GET' => [
    '/' => 'App\Controllers\AuthController::index',
    '/logout' => 'App\Controllers\AuthController::logout',
    '/dashboard' => 'App\Controllers\DashboardController::index',
    '/users' => 'App\Controllers\UserController::index',
    '/users/{id}' => 'App\Controllers\UserController::details',
    '/users/{id}/delete' => 'App\Controllers\UserController::deleteUser',
    '/roles' => 'App\Controllers\RoleController::index',
    '/categories' => 'App\Controllers\CategoryController::index',
    '/inventory' => 'App\Controllers\InventoryController::index',
    '/products/{id}' => 'App\Controllers\ProductsController::details',
    '/products/{id}/delete' => 'App\Controllers\ProductsController::deleteProduct',
    '/customers' => 'App\Controllers\CustomerController::index',
    '/suppliers' => 'App\Controllers\SupplierController::index',
    '/suppliers/{id}' => 'App\Controllers\SupplierController::details',
    '/suppliers/{id}/delete' => 'App\Controllers\SupplierController::deleteSupplier',
    '/orders' => 'App\Controllers\OrderController::index',
    '/discounts' => 'App\Controllers\DiscountController::index',
    '/reports' => 'App\Controllers\ReportController::index',
    '/employees' => 'App\Controllers\EmployeeController::index',
    '/pos' => 'App\Controllers\POSController::index',
    '/api/pos/search' => 'App\Controllers\POSController::searchProducts',
    '/api/category/search' => 'App\Controllers\CategoryController::search',
    '/api/pos/customer/search' => 'App\Controllers\CustomerController::search',
    '/api/suppliers/search' => 'App\Controllers\SupplierController::search',
    '/api/suppliers/{id}/products/search' => 'App\Controllers\SupplierController::searchProducts',
    '/api/products/search' => 'App\Controllers\ProductsController::search',
    '/api/inventory/search' => 'App\Controllers\InventoryController::searchproducts',
  ],

  'POST' => [
    '/' => 'App\Controllers\AuthController::login',
    '/customers/new' => 'App\Controllers\CustomerController::createCustomer',
    '/users/new' => 'App\Controllers\UserController::createUser',
    '/users/{id}/update' => 'App\Controllers\UserController::updateUser',
    '/suppliers/new' => 'App\Controllers\SupplierController::createSupplier',
    '/suppliers/{id}/update' => 'App\Controllers\SupplierController::updateSupplier',
    '/products/new' => 'App\Controllers\ProductsController::createProduct',
    '/products/{id}/update' => 'App\Controllers\ProductsController::updateProduct',
    '/api/pos/checkout' => 'App\Controllers\POSController::checkout',
    '/batch/new' => 'App\Controllers\BatchController::createBatch',
    '/batch/{id}/update' => 'App\Controllers\BatchController::updateBatch',
    '/orders/new' => 'App\Controllers\OrderController::createOrder',
  ],
];
