<?php

return [
  'GET' => [
    '/' => 'App\Controllers\AuthController::index',
    '/logout' => 'App\Controllers\AuthController::logout',
    '/dashboard' => 'App\Controllers\DashboardController::index',
    '/users' => 'App\Controllers\UserController::index',
    '/profile' => 'App\Controllers\UserController::profile',
    '/users/{id}' => 'App\Controllers\UserController::details',
    '/users/{id}/delete' => 'App\Controllers\UserController::deleteUser',
    '/roles' => 'App\Controllers\RoleController::index',
    '/categories' => 'App\Controllers\CategoryController::index',
    '/inventory' => 'App\Controllers\InventoryController::index',
    '/products/{id}' => 'App\Controllers\ProductsController::details',
    '/products/{id}/delete' => 'App\Controllers\ProductsController::deleteProduct',
    '/customers' => 'App\Controllers\CustomerController::index',
    '/suppliers' => 'App\Controllers\SupplierController::index',
    '/suppliers/{id}' => 'App\Controllers\SupplierController::details',
    '/suppliers/{id}/delete' => 'App\Controllers\SupplierController::deleteSupplier',
    '/orders' => 'App\Controllers\OrderController::index',
    '/orders/{id}' => 'App\Controllers\OrderController::details',
    '/orders/{id}/delete' => 'App\Controllers\OrderController::deleteOrder',
    '/orders/{id}/approve' => 'App\Controllers\OrderController::approveOrder',
    '/orders/{id}/complete' => 'App\Controllers\OrderController::completeOrder',
    '/orders/{id}/cancel' => 'App\Controllers\OrderController::cancelOrder',
    '/discounts' => 'App\Controllers\DiscountsController::index',
    '/discounts/{id}/delete' => 'App\Controllers\DiscountsController::deleteDiscount',
    '/discounts/{id}/activate' => 'App\Controllers\DiscountsController::activateDiscount',
    '/discounts/{id}/deactivate' => 'App\Controllers\DiscountsController::deactivateDiscount',
    '/reports' => 'App\Controllers\ReportController::index',
    '/employees' => 'App\Controllers\EmployeeController::index',
    '/pos' => 'App\Controllers\POSController::index',
    '/api/pos/search' => 'App\Controllers\POSController::searchProducts',
    '/api/category/search' => 'App\Controllers\CategoryController::search',
    '/api/pos/customer/search' => 'App\Controllers\CustomerController::search',
    '/api/suppliers/search' => 'App\Controllers\SupplierController::search',
    '/api/suppliers/{id}/products/search' => 'App\Controllers\SupplierController::searchProducts',
    '/api/products/search' => 'App\Controllers\ProductsController::searchProducts',
    '/batch/{id}/delete' => 'App\Controllers\BatchController::deleteBatch',
    '/categories/{id}/delete' => 'App\Controllers\CategoryController::deleteCategory',
    '/notifications' => 'App\Controllers\NotificationController::index',
    '/products/{id}/placeorder' => 'App\Controllers\ProductsController::placeOrder',
    '/branches' => 'App\Controllers\BranchController::index',
    '/branches/{id}/deactivate' => 'App\Controllers\BranchController::deactivateBranch',
    '/branches/{id}/restore' => 'App\Controllers\BranchController::restoreBranch', 

  ],

  'POST' => [
    '/' => 'App\Controllers\AuthController::login',
    '/customers/new' => 'App\Controllers\CustomerController::createCustomer',
    '/users/new' => 'App\Controllers\UserController::createUser',
    '/users/{id}/update' => 'App\Controllers\UserController::updateUser',
    '/users/{id}/reset-password' => 'App\Controllers\UserController::updatePassword',
    '/profile/update' => 'App\Controllers\UserController::updateProfile',
    '/profile/reset-password' => 'App\Controllers\UserController::updateProfilePassword',
    '/suppliers/new' => 'App\Controllers\SupplierController::createSupplier',
    '/suppliers/{id}/update' => 'App\Controllers\SupplierController::updateSupplier',
    '/suppliers/{id}/products' => 'App\Controllers\SupplierController::assignProduct',
    '/suppliers/{id}/products/delete' => 'App\Controllers\SupplierController::deleteAssignedProduct',
    '/products/new' => 'App\Controllers\ProductsController::createProduct',
    '/products/{id}/update' => 'App\Controllers\ProductsController::updateProduct',
    '/api/pos/checkout' => 'App\Controllers\POSController::checkout',
    '/api/pos/discounts/get' => 'App\Controllers\DiscountsController::getDiscounts',
    '/batch/new' => 'App\Controllers\BatchController::createBatch',
    '/batch/{id}/update' => 'App\Controllers\BatchController::updateBatch',
    '/roles/new' => 'App\Controllers\RoleController::addRole',
    '/roles/{id}/update' => 'App\Controllers\RoleController::updateRole',
    '/roles/{id}/delete' => 'App\Controllers\RoleController::deleteRole',
    '/orders/new' => 'App\Controllers\OrderController::createOrder',
    '/categories/new' => 'App\Controllers\CategoryController::createCategory',
    '/categories/{id}/update' => 'App\Controllers\CategoryController::updateCategory',
    '/orders/{id}/update' => 'App\Controllers\OrderController::updateOrder',
    '/orders/{id}/receive' => 'App\Controllers\OrderController::receiveOrder',
    '/discounts/new' => 'App\Controllers\DiscountsController::createDiscount',
    '/discounts/{id}/update' => 'App\Controllers\DiscountsController::updateDiscount',
    '/api/notifications/mark-read' => 'App\Controllers\NotificationController::markAsRead',
    '/api/notifications/mark-all-read' => 'App\Controllers\NotificationController::markAllAsRead',
    '/branches/new' => 'App\Controllers\BranchController::createBranch',
    '/branches/{id}/update' => 'App\Controllers\BranchController::updateBranch',
  ],
];

